apiVersion: v1
kind: Pod
metadata:
  name: mod-synth-{POD_NUM}
  namespace: gai-lina-group
  labels:
    app: mod-synth
spec:
  nodeSelector:
    nautilus.io/linstor: "true"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.product
            operator: In
            values:
            - NVIDIA-A10
            - NVIDIA-GeForce-RTX-3090
            - NVIDIA-GeForce-RTX-4090
            - NVIDIA-TITAN-RTX
            - NVIDIA-RTX-A5000
            - Quadro-RTX-6000
            - Tesla-V100-SXM2-32GB
            - NVIDIA-A40
            - NVIDIA-L40
            - NVIDIA-RTX-A6000
            - Quadro-RTX-8000
  tolerations:
    - key: nvidia.com/gpu
      operator: Exists
    - key: nvidia.com/gpu
      operator: Exists
      effect: PreferNoSchedule
  containers:
  - name: sweep-agent
    image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/prp
   
    command: ["/bin/bash", "-c"]
    args:
      - |
        sudo apt-get update && sudo apt-get install -y git wget p7zip-full
       
        git clone -b 9sweep https://github.com/tsereda/wavelet-brats-synthesis.git
        cd wavelet-brats-synthesis
       
        chmod -R 777 /checkpoints
        chown -R 1000:100 /checkpoints
       
        chmod +x run.sh
       
        ./run.sh
        tail -f /dev/null
   
    env:
    - name: WANDB_API_KEY
      valueFrom:
        secretKeyRef:
          name: wandb-credentials
          key: api-key
    - name: WANDB_ENTITY
      value: "timgsereda"
    - name: WANDB_PROJECT
      value: "wavelet-brats-synthesis"
    - name: SWEEP_ID
      value: "{SWEEP_ID}"
    - name: WANDB_SWEEP_ID
      value: "{SWEEP_ID}"
   
    resources:
      requests:
        memory: "16Gi"
        cpu: "4"
        nvidia.com/gpu: "1"
      limits:
        memory: "32Gi"
        cpu: "8"
        nvidia.com/gpu: "1"
   
    volumeMounts:
    - name: data-volume
      mountPath: /data
 
    - name: checkpoints
      mountPath: /checkpoints
    - name: shm
      mountPath: /dev/shm
 
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: brats2025-{POD_NUM}
  - name: checkpoints
    persistentVolumeClaim:
      claimName: brats-checkpoints
  - name: shm
    emptyDir:
      medium: Memory
      sizeLimit: 16Gi