apiVersion: batch/v1
kind: Job
metadata:
  name: midslice-1
  namespace: gai-lina-group
  labels:
    app: tim.wandb-sweep
spec:
  template:
    spec:
      nodeSelector:
        nautilus.io/linstor: "true"
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
        - key: nvidia.com/gpu
          operator: Exists
          effect: PreferNoSchedule
      containers:
      - name: sweep-agent
        image: nvcr.io/nvidia/pytorch:24.09-py3
      
        command: ["/bin/bash", "-c"]
        args:
          - |
            sudo apt-get update && sudo apt-get install -y git wget p7zip-full
            pip install wandb monai
            pip install nibabel>=5.0.0
            apt update
            apt install p7zip-full -y

            # Reinstall monai with nibabel support
            pip install --upgrade "monai[nibabel]>=1.3.0"
            pip install einops>=0.7.0
            pip install blobfile
            pip install scikit-image
          
            git clone -b exp https://github.com/tsereda/wavelet-brats-synthesis.git
            cd wavelet-brats-synthesis/slice-prediction


            7z x /data/ASNR-MICCAI-BraTS2023-GLI-MET-TrainingData.tar.gz -O.
            7z x ASNR-MICCAI-BraTS2023-GLI-MET-TrainingData.tar -o.
            pip install PyWavelets
            wandb agent timgsereda/wavelet-brats-synthesis-slice-prediction/s0t15ka8

      
        env:
        - name: WANDB_API_KEY
          valueFrom:
            secretKeyRef:
              name: wandb-credentials
              key: api-key
        - name: WANDB_ENTITY
          value: "timgsereda"
        - name: WANDB_PROJECT
          value: "wavelet-brats-synthesis"
        resources:
          requests:
            memory: "50Gi"
            cpu: "15"
            nvidia.com/a100: "1"
          limits:
            memory: "60Gi"
            cpu: "18"
            nvidia.com/a100: "1"
      
        volumeMounts:
        - name: data-volume
          mountPath: /data
        - name: shm
          mountPath: /dev/shm
    
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: brats2025-1
      - name: shm
        emptyDir:
          medium: Memory
          sizeLimit: 16Gi

      restartPolicy: Never